runtime: python311
entrypoint: gunicorn -b :8080 -w 2 main:app
manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
service: rag-flask-front
service_account: app-engine-flex@gpeg-externalization-platform.iam.gserviceaccount.com
